FROM node:latest

COPY . /var/www/hashlottery/

WORKDIR /var/www/hashlottery/

RUN npm install

RUN npm run build

CMD cp -rp /var/www/hashlottery/* /var/www/front-dev/ && cp /var/www/hashlottery/.htaccess /var/www/front-dev/