FROM node:latest

COPY . /var/www/hashlottery/

WORKDIR /var/www/hashlottery/

RUN npm install && npm i -g gulp

RUN npm rebuild node-sass

RUN gulp

CMD cp -rp /var/www/hashlottery/build /var/www/front-dev/